name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        # make depends on uv
      - name: Install dependencies
        run: |
          pip install uv
          uv sync
          uv add pytest-cov
      - name: Run linter
        run: |
          uv run ruff check
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageCommand: uv run pytest --cov --cov-report xml
          debug: true
